// The HarnessRegistry admin API: register, inspect and retire harnesses on a running host.
//
// A registration is immutable. Its spec is content-addressed by spec_digest, so registering the
// same spec under the same name again changes nothing, and a different spec under a taken name is
// refused. Retiring a harness refuses new sessions on it while every existing session keeps
// running, resuming and forking. Registering the identical spec again reactivates it.
//
// This service decides what the host dials and pays model calls for, so it is an operator
// surface, not a client one. agentsessionsd does not serve it; see docs/security.md.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: harness_registry.proto

package agentsessionsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HarnessState int32

const (
	HarnessState_HARNESS_STATE_UNSPECIFIED HarnessState = 0
	// New sessions may select it.
	HarnessState_HARNESS_STATE_ACTIVE HarnessState = 1
	// New sessions are refused with FAILED_PRECONDITION. Existing sessions keep Exec, Resume, Suspend
	// and Fork; fork children inherit the harness and are not new selections.
	HarnessState_HARNESS_STATE_RETIRED HarnessState = 2
)

// Enum value maps for HarnessState.
var (
	HarnessState_name = map[int32]string{
		0: "HARNESS_STATE_UNSPECIFIED",
		1: "HARNESS_STATE_ACTIVE",
		2: "HARNESS_STATE_RETIRED",
	}
	HarnessState_value = map[string]int32{
		"HARNESS_STATE_UNSPECIFIED": 0,
		"HARNESS_STATE_ACTIVE":      1,
		"HARNESS_STATE_RETIRED":     2,
	}
)

func (x HarnessState) Enum() *HarnessState {
	p := new(HarnessState)
	*p = x
	return p
}

func (x HarnessState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HarnessState) Descriptor() protoreflect.EnumDescriptor {
	return file_harness_registry_proto_enumTypes[0].Descriptor()
}

func (HarnessState) Type() protoreflect.EnumType {
	return &file_harness_registry_proto_enumTypes[0]
}

func (x HarnessState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HarnessState.Descriptor instead.
func (HarnessState) EnumDescriptor() ([]byte, []int) {
	return file_harness_registry_proto_rawDescGZIP(), []int{0}
}

type HarnessSource int32

const (
	HarnessSource_HARNESS_SOURCE_UNSPECIFIED HarnessSource = 0
	// Built into the host or configured when it started. Never stored, always ACTIVE, and read-only
	// through this API: its name cannot be registered or retired.
	HarnessSource_HARNESS_SOURCE_STATIC HarnessSource = 1
	// Created through RegisterHarness and stored in the host's journal database.
	HarnessSource_HARNESS_SOURCE_REGISTERED HarnessSource = 2
)

// Enum value maps for HarnessSource.
var (
	HarnessSource_name = map[int32]string{
		0: "HARNESS_SOURCE_UNSPECIFIED",
		1: "HARNESS_SOURCE_STATIC",
		2: "HARNESS_SOURCE_REGISTERED",
	}
	HarnessSource_value = map[string]int32{
		"HARNESS_SOURCE_UNSPECIFIED": 0,
		"HARNESS_SOURCE_STATIC":      1,
		"HARNESS_SOURCE_REGISTERED":  2,
	}
)

func (x HarnessSource) Enum() *HarnessSource {
	p := new(HarnessSource)
	*p = x
	return p
}

func (x HarnessSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HarnessSource) Descriptor() protoreflect.EnumDescriptor {
	return file_harness_registry_proto_enumTypes[1].Descriptor()
}

func (HarnessSource) Type() protoreflect.EnumType {
	return &file_harness_registry_proto_enumTypes[1]
}

func (x HarnessSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HarnessSource.Descriptor instead.
func (HarnessSource) EnumDescriptor() ([]byte, []int) {
	return file_harness_registry_proto_rawDescGZIP(), []int{1}
}

type RegisterOutcome int32

const (
	RegisterOutcome_REGISTER_OUTCOME_UNSPECIFIED RegisterOutcome = 0
	// The name was free; the registration is new and ACTIVE.
	RegisterOutcome_REGISTER_OUTCOME_CREATED RegisterOutcome = 1
	// The name already held this spec and was ACTIVE. Nothing changed.
	RegisterOutcome_REGISTER_OUTCOME_UNCHANGED RegisterOutcome = 2
	// The name already held this spec and was RETIRED. It is ACTIVE again.
	RegisterOutcome_REGISTER_OUTCOME_REACTIVATED RegisterOutcome = 3
)

// Enum value maps for RegisterOutcome.
var (
	RegisterOutcome_name = map[int32]string{
		0: "REGISTER_OUTCOME_UNSPECIFIED",
		1: "REGISTER_OUTCOME_CREATED",
		2: "REGISTER_OUTCOME_UNCHANGED",
		3: "REGISTER_OUTCOME_REACTIVATED",
	}
	RegisterOutcome_value = map[string]int32{
		"REGISTER_OUTCOME_UNSPECIFIED": 0,
		"REGISTER_OUTCOME_CREATED":     1,
		"REGISTER_OUTCOME_UNCHANGED":   2,
		"REGISTER_OUTCOME_REACTIVATED": 3,
	}
)

func (x RegisterOutcome) Enum() *RegisterOutcome {
	p := new(RegisterOutcome)
	*p = x
	return p
}

func (x RegisterOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegisterOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_harness_registry_proto_enumTypes[2].Descriptor()
}

func (RegisterOutcome) Type() protoreflect.EnumType {
	return &file_harness_registry_proto_enumTypes[2]
}

func (x RegisterOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegisterOutcome.Descriptor instead.
func (RegisterOutcome) EnumDescriptor() ([]byte, []int) {
	return file_harness_registry_proto_rawDescGZIP(), []int{2}
}

// RemotePlacement is a harness already running at address, dialed over the Harness service.
type RemotePlacement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// unix:///path/to.sock or host:port.
	Address       string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemotePlacement) Reset() {
	*x = RemotePlacement{}
	mi := &file_harness_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemotePlacement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemotePlacement) ProtoMessage() {}

func (x *RemotePlacement) ProtoReflect() protoreflect.Message {
	mi := &file_harness_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemotePlacement.ProtoReflect.Descriptor instead.
func (*RemotePlacement) Descriptor() ([]byte, []int) {
	return file_harness_registry_proto_rawDescGZIP(), []int{0}
}

func (x *RemotePlacement) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// SubstratePlacement runs each session in its own actor created from an ActorTemplate. A host
// serves it only if it was built with a substrate placement backend; otherwise RegisterHarness
// returns FAILED_PRECONDITION.
type SubstratePlacement struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Atespace string                 `protobuf:"bytes,1,opt,name=atespace,proto3" json:"atespace,omitempty"`
	// ActorTemplate name.
	Template      string `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubstratePlacement) Reset() {
	*x = SubstratePlacement{}
	mi := &file_harness_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubstratePlacement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubstratePlacement) ProtoMessage() {}

func (x *SubstratePlacement) ProtoReflect() protoreflect.Message {
	mi := &file_harness_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubstratePlacement.ProtoReflect.Descriptor instead.
func (*SubstratePlacement) Descriptor() ([]byte, []int) {
	return file_harness_registry_proto_rawDescGZIP(), []int{1}
}

func (x *SubstratePlacement) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

func (x *SubstratePlacement) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

// HarnessSpec is everything that decides what a session on this harness runs. It is the only
// input to spec_digest, so nothing descriptive (labels, operation ids, timestamps) belongs here.
type HarnessSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exactly one is required.
	//
	// Types that are valid to be assigned to Placement:
	//
	//	*HarnessSpec_Remote
	//	*HarnessSpec_Substrate
	Placement isHarnessSpec_Placement `protobuf_oneof:"placement"`
	// The contract the harness declares. resumability is required. Placement still gates every turn
	// on the capabilities the harness reports through Describe.
	Capabilities *Capabilities `protobuf:"bytes,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Expected HarnessDescriptor.id. When set, Exec, Resume and Fork are refused with
	// FAILED_PRECONDITION, before anything is journaled, if the harness's Describe reports a different
	// id. It is checked on every call, not at registration. Empty means not checked. The id is what
	// the harness reports about itself, so this catches an address that reaches the wrong harness; it
	// is not authentication.
	DescriptorId  string `protobuf:"bytes,4,opt,name=descriptor_id,json=descriptorId,proto3" json:"descriptor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HarnessSpec) Reset() {
	*x = HarnessSpec{}
	mi := &file_harness_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarnessSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarnessSpec) ProtoMessage() {}

func (x *HarnessSpec) ProtoReflect() protoreflect.Message {
	mi := &file_harness_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarnessSpec.ProtoReflect.Descriptor instead.
func (*HarnessSpec) Descriptor() ([]byte, []int) {
	return file_harness_registry_proto_rawDescGZIP(), []int{2}
}

func (x *HarnessSpec) GetPlacement() isHarnessSpec_Placement {
	if x != nil {
		return x.Placement
	}
	return nil
}

func (x *HarnessSpec) GetRemote() *RemotePlacement {
	if x != nil {
		if x, ok := x.Placement.(*HarnessSpec_Remote); ok {
			return x.Remote
		}
	}
	return nil
}

func (x *HarnessSpec) GetSubstrate() *SubstratePlacement {
	if x != nil {
		if x, ok := x.Placement.(*HarnessSpec_Substrate); ok {
			return x.Substrate
		}
	}
	return nil
}

func (x *HarnessSpec) GetCapabilities() *Capabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *HarnessSpec) GetDescriptorId() string {
	if x != nil {
		return x.DescriptorId
	}
	return ""
}

type isHarnessSpec_Placement interface {
	isHarnessSpec_Placement()
}

type HarnessSpec_Remote struct {
	Remote *RemotePlacement `protobuf:"bytes,1,opt,name=remote,proto3,oneof"`
}

type HarnessSpec_Substrate struct {
	Substrate *SubstratePlacement `protobuf:"bytes,2,opt,name=substrate,proto3,oneof"`
}

func (*HarnessSpec_Remote) isHarnessSpec_Placement() {}

func (*HarnessSpec_Substrate) isHarnessSpec_Placement() {}

// HarnessRegistration is one entry in the host's harness registry.
type HarnessRegistration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// metadata.name is the key that Session.harness and ExecRequest.harness refer to. metadata.uid is
	// server-assigned and stays the same across UNCHANGED and REACTIVATED. metadata.project is
	// unused: a registration is host-scoped.
	Metadata *ResourceMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Unset for a STATIC harness, or for a stored registration whose spec this host cannot decode
	// or validate. No partial spec is returned in the latter case; see unservable_reason.
	Spec *HarnessSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	// "sha256:" followed by the lowercase hex SHA-256 of the RFC 8785 (JCS) form of the
	// originally stored spec's proto3-JSON mapping, with proto field names, enum names, and
	// unpopulated fields omitted. This is the same canonical form the journal hashes. Empty for a
	// STATIC harness. Preserved when spec is unset for an undecodable registration: this host
	// cannot recompute the original digest without understanding the complete spec.
	SpecDigest string        `protobuf:"bytes,3,opt,name=spec_digest,json=specDigest,proto3" json:"spec_digest,omitempty"`
	State      HarnessState  `protobuf:"varint,4,opt,name=state,proto3,enum=agentsessions.v1.HarnessState" json:"state,omitempty"`
	Source     HarnessSource `protobuf:"varint,5,opt,name=source,proto3,enum=agentsessions.v1.HarnessSource" json:"source,omitempty"`
	// Set while RETIRED: when the harness was first retired.
	RetireTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=retire_time,json=retireTime,proto3" json:"retire_time,omitempty"`
	// Set while RETIRED: the reason given when the harness was first retired.
	RetireReason string `protobuf:"bytes,7,opt,name=retire_reason,json=retireReason,proto3" json:"retire_reason,omitempty"`
	// Set only when GetHarnessRequest.observe is true and Describe succeeded: what the harness
	// reported just now. Never stored.
	Observed *HarnessDescriptor `protobuf:"bytes,8,opt,name=observed,proto3" json:"observed,omitempty"`
	// Set only when GetHarnessRequest.observe is true and Describe failed: why.
	ObserveError string `protobuf:"bytes,9,opt,name=observe_error,json=observeError,proto3" json:"observe_error,omitempty"`
	// Nonempty if this host cannot serve a registered harness (including a row added by another
	// host after startup, which requires a restart here). The registration remains visible and its
	// name reserved, ACTIVE or RETIRED; Sessions operations needing it fail FAILED_PRECONDITION.
	// Strict decoding refuses unsupported stored fields and enum values, rather than accepting a
	// partial spec. This is a host-local status, never stored: another compatible host may serve the
	// same registration. Do not match on this human-readable explanation.
	UnservableReason string `protobuf:"bytes,10,opt,name=unservable_reason,json=unservableReason,proto3" json:"unservable_reason,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HarnessRegistration) Reset() {
	*x = HarnessRegistration{}
	mi := &file_harness_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HarnessRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HarnessRegistration) ProtoMessage() {}

func (x *HarnessRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_harness_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HarnessRegistration.ProtoReflect.Descriptor instead.
func (*HarnessRegistration) Descriptor() ([]byte, []int) {
	return file_harness_registry_proto_rawDescGZIP(), []int{3}
}

func (x *HarnessRegistration) GetMetadata() *ResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *HarnessRegistration) GetSpec() *HarnessSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *HarnessRegistration) GetSpecDigest() string {
	if x != nil {
		return x.SpecDigest
	}
	return ""
}

func (x *HarnessRegistration) GetState() HarnessState {
	if x != nil {
		return x.State
	}
	return HarnessState_HARNESS_STATE_UNSPECIFIED
}

func (x *HarnessRegistration) GetSource() HarnessSource {
	if x != nil {
		return x.Source
	}
	return HarnessSource_HARNESS_SOURCE_UNSPECIFIED
}

func (x *HarnessRegistration) GetRetireTime() *timestamppb.Timestamp {
	if x != nil {
		return x.RetireTime
	}
	return nil
}

func (x *HarnessRegistration) GetRetireReason() string {
	if x != nil {
		return x.RetireReason
	}
	return ""
}

func (x *HarnessRegistration) GetObserved() *HarnessDescriptor {
	if x != nil {
		return x.Observed
	}
	return nil
}

func (x *HarnessRegistration) GetObserveError() string {
	if x != nil {
		return x.ObserveError
	}
	return ""
}

func (x *HarnessRegistration) GetUnservableReason() string {
	if x != nil {
		return x.UnservableReason
	}
	return ""
}

type RegisterHarnessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An RFC 1123 DNS label: lowercase alphanumerics and '-', starting and ending alphanumeric, at
	// most 63 characters.
	Name          string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Spec          *HarnessSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterHarnessRequest) Reset() {
	*x = RegisterHarnessRequest{}
	mi := &file_harness_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterHarnessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterHarnessRequest) ProtoMessage() {}

func (x *RegisterHarnessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harness_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterHarnessRequest.ProtoReflect.Descriptor instead.
func (*RegisterHarnessRequest) Descriptor() ([]byte, []int) {
	return file_harness_registry_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterHarnessRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterHarnessRequest) GetSpec() *HarnessSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type RegisterHarnessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Harness       *HarnessRegistration   `protobuf:"bytes,1,opt,name=harness,proto3" json:"harness,omitempty"`
	Outcome       RegisterOutcome        `protobuf:"varint,2,opt,name=outcome,proto3,enum=agentsessions.v1.RegisterOutcome" json:"outcome,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterHarnessResponse) Reset() {
	*x = RegisterHarnessResponse{}
	mi := &file_harness_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterHarnessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterHarnessResponse) ProtoMessage() {}

func (x *RegisterHarnessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_harness_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterHarnessResponse.ProtoReflect.Descriptor instead.
func (*RegisterHarnessResponse) Descriptor() ([]byte, []int) {
	return file_harness_registry_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterHarnessResponse) GetHarness() *HarnessRegistration {
	if x != nil {
		return x.Harness
	}
	return nil
}

func (x *RegisterHarnessResponse) GetOutcome() RegisterOutcome {
	if x != nil {
		return x.Outcome
	}
	return RegisterOutcome_REGISTER_OUTCOME_UNSPECIFIED
}

type GetHarnessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Also ask the harness to Describe itself, bounded by a host timeout. The result is in observed
	// or observe_error; a failed Describe does not fail the call.
	Observe       bool `protobuf:"varint,2,opt,name=observe,proto3" json:"observe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHarnessRequest) Reset() {
	*x = GetHarnessRequest{}
	mi := &file_harness_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHarnessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHarnessRequest) ProtoMessage() {}

func (x *GetHarnessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harness_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHarnessRequest.ProtoReflect.Descriptor instead.
func (*GetHarnessRequest) Descriptor() ([]byte, []int) {
	return file_harness_registry_proto_rawDescGZIP(), []int{6}
}

func (x *GetHarnessRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetHarnessRequest) GetObserve() bool {
	if x != nil {
		return x.Observe
	}
	return false
}

type ListHarnessesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum entries per page. 0 means 50; values above 500 are clamped to 500. Negative is
	// INVALID_ARGUMENT.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Opaque cursor from a prior ListHarnessesResponse.next_page_token. Empty means the first page.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Include RETIRED entries. STATIC entries are always included.
	IncludeRetired bool `protobuf:"varint,3,opt,name=include_retired,json=includeRetired,proto3" json:"include_retired,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListHarnessesRequest) Reset() {
	*x = ListHarnessesRequest{}
	mi := &file_harness_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHarnessesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHarnessesRequest) ProtoMessage() {}

func (x *ListHarnessesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harness_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHarnessesRequest.ProtoReflect.Descriptor instead.
func (*ListHarnessesRequest) Descriptor() ([]byte, []int) {
	return file_harness_registry_proto_rawDescGZIP(), []int{7}
}

func (x *ListHarnessesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListHarnessesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListHarnessesRequest) GetIncludeRetired() bool {
	if x != nil {
		return x.IncludeRetired
	}
	return false
}

type ListHarnessesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// In name order, STATIC and REGISTERED entries together.
	Harnesses []*HarnessRegistration `protobuf:"bytes,1,rep,name=harnesses,proto3" json:"harnesses,omitempty"`
	// Empty on the last page.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHarnessesResponse) Reset() {
	*x = ListHarnessesResponse{}
	mi := &file_harness_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHarnessesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHarnessesResponse) ProtoMessage() {}

func (x *ListHarnessesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_harness_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHarnessesResponse.ProtoReflect.Descriptor instead.
func (*ListHarnessesResponse) Descriptor() ([]byte, []int) {
	return file_harness_registry_proto_rawDescGZIP(), []int{8}
}

func (x *ListHarnessesResponse) GetHarnesses() []*HarnessRegistration {
	if x != nil {
		return x.Harnesses
	}
	return nil
}

func (x *ListHarnessesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type RetireHarnessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Recorded on the first retire only.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetireHarnessRequest) Reset() {
	*x = RetireHarnessRequest{}
	mi := &file_harness_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetireHarnessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetireHarnessRequest) ProtoMessage() {}

func (x *RetireHarnessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_harness_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetireHarnessRequest.ProtoReflect.Descriptor instead.
func (*RetireHarnessRequest) Descriptor() ([]byte, []int) {
	return file_harness_registry_proto_rawDescGZIP(), []int{9}
}

func (x *RetireHarnessRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RetireHarnessRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_harness_registry_proto protoreflect.FileDescriptor

const file_harness_registry_proto_rawDesc = "" +
	"\n" +
	"\x16harness_registry.proto\x12\x10agentsessions.v1\x1a\fcommon.proto\x1a\rharness.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"+\n" +
	"\x0fRemotePlacement\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"L\n" +
	"\x12SubstratePlacement\x12\x1a\n" +
	"\batespace\x18\x01 \x01(\tR\batespace\x12\x1a\n" +
	"\btemplate\x18\x02 \x01(\tR\btemplate\"\x86\x02\n" +
	"\vHarnessSpec\x12;\n" +
	"\x06remote\x18\x01 \x01(\v2!.agentsessions.v1.RemotePlacementH\x00R\x06remote\x12D\n" +
	"\tsubstrate\x18\x02 \x01(\v2$.agentsessions.v1.SubstratePlacementH\x00R\tsubstrate\x12B\n" +
	"\fcapabilities\x18\x03 \x01(\v2\x1e.agentsessions.v1.CapabilitiesR\fcapabilities\x12#\n" +
	"\rdescriptor_id\x18\x04 \x01(\tR\fdescriptorIdB\v\n" +
	"\tplacement\"\x8d\x04\n" +
	"\x13HarnessRegistration\x12>\n" +
	"\bmetadata\x18\x01 \x01(\v2\".agentsessions.v1.ResourceMetadataR\bmetadata\x121\n" +
	"\x04spec\x18\x02 \x01(\v2\x1d.agentsessions.v1.HarnessSpecR\x04spec\x12\x1f\n" +
	"\vspec_digest\x18\x03 \x01(\tR\n" +
	"specDigest\x124\n" +
	"\x05state\x18\x04 \x01(\x0e2\x1e.agentsessions.v1.HarnessStateR\x05state\x127\n" +
	"\x06source\x18\x05 \x01(\x0e2\x1f.agentsessions.v1.HarnessSourceR\x06source\x12;\n" +
	"\vretire_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"retireTime\x12#\n" +
	"\rretire_reason\x18\a \x01(\tR\fretireReason\x12?\n" +
	"\bobserved\x18\b \x01(\v2#.agentsessions.v1.HarnessDescriptorR\bobserved\x12#\n" +
	"\robserve_error\x18\t \x01(\tR\fobserveError\x12+\n" +
	"\x11unservable_reason\x18\n" +
	" \x01(\tR\x10unservableReason\"_\n" +
	"\x16RegisterHarnessRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x121\n" +
	"\x04spec\x18\x02 \x01(\v2\x1d.agentsessions.v1.HarnessSpecR\x04spec\"\x97\x01\n" +
	"\x17RegisterHarnessResponse\x12?\n" +
	"\aharness\x18\x01 \x01(\v2%.agentsessions.v1.HarnessRegistrationR\aharness\x12;\n" +
	"\aoutcome\x18\x02 \x01(\x0e2!.agentsessions.v1.RegisterOutcomeR\aoutcome\"A\n" +
	"\x11GetHarnessRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aobserve\x18\x02 \x01(\bR\aobserve\"{\n" +
	"\x14ListHarnessesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12'\n" +
	"\x0finclude_retired\x18\x03 \x01(\bR\x0eincludeRetired\"\x84\x01\n" +
	"\x15ListHarnessesResponse\x12C\n" +
	"\tharnesses\x18\x01 \x03(\v2%.agentsessions.v1.HarnessRegistrationR\tharnesses\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"B\n" +
	"\x14RetireHarnessRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason*b\n" +
	"\fHarnessState\x12\x1d\n" +
	"\x19HARNESS_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14HARNESS_STATE_ACTIVE\x10\x01\x12\x19\n" +
	"\x15HARNESS_STATE_RETIRED\x10\x02*i\n" +
	"\rHarnessSource\x12\x1e\n" +
	"\x1aHARNESS_SOURCE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HARNESS_SOURCE_STATIC\x10\x01\x12\x1d\n" +
	"\x19HARNESS_SOURCE_REGISTERED\x10\x02*\x93\x01\n" +
	"\x0fRegisterOutcome\x12 \n" +
	"\x1cREGISTER_OUTCOME_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18REGISTER_OUTCOME_CREATED\x10\x01\x12\x1e\n" +
	"\x1aREGISTER_OUTCOME_UNCHANGED\x10\x02\x12 \n" +
	"\x1cREGISTER_OUTCOME_REACTIVATED\x10\x032\x95\x03\n" +
	"\x0fHarnessRegistry\x12f\n" +
	"\x0fRegisterHarness\x12(.agentsessions.v1.RegisterHarnessRequest\x1a).agentsessions.v1.RegisterHarnessResponse\x12X\n" +
	"\n" +
	"GetHarness\x12#.agentsessions.v1.GetHarnessRequest\x1a%.agentsessions.v1.HarnessRegistration\x12`\n" +
	"\rListHarnesses\x12&.agentsessions.v1.ListHarnessesRequest\x1a'.agentsessions.v1.ListHarnessesResponse\x12^\n" +
	"\rRetireHarness\x12&.agentsessions.v1.RetireHarnessRequest\x1a%.agentsessions.v1.HarnessRegistrationB<Z:github.com/aramase/agentsessions/api/genpb;agentsessionsv1b\x06proto3"

var (
	file_harness_registry_proto_rawDescOnce sync.Once
	file_harness_registry_proto_rawDescData []byte
)

func file_harness_registry_proto_rawDescGZIP() []byte {
	file_harness_registry_proto_rawDescOnce.Do(func() {
		file_harness_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_harness_registry_proto_rawDesc), len(file_harness_registry_proto_rawDesc)))
	})
	return file_harness_registry_proto_rawDescData
}

var file_harness_registry_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_harness_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_harness_registry_proto_goTypes = []any{
	(HarnessState)(0),               // 0: agentsessions.v1.HarnessState
	(HarnessSource)(0),              // 1: agentsessions.v1.HarnessSource
	(RegisterOutcome)(0),            // 2: agentsessions.v1.RegisterOutcome
	(*RemotePlacement)(nil),         // 3: agentsessions.v1.RemotePlacement
	(*SubstratePlacement)(nil),      // 4: agentsessions.v1.SubstratePlacement
	(*HarnessSpec)(nil),             // 5: agentsessions.v1.HarnessSpec
	(*HarnessRegistration)(nil),     // 6: agentsessions.v1.HarnessRegistration
	(*RegisterHarnessRequest)(nil),  // 7: agentsessions.v1.RegisterHarnessRequest
	(*RegisterHarnessResponse)(nil), // 8: agentsessions.v1.RegisterHarnessResponse
	(*GetHarnessRequest)(nil),       // 9: agentsessions.v1.GetHarnessRequest
	(*ListHarnessesRequest)(nil),    // 10: agentsessions.v1.ListHarnessesRequest
	(*ListHarnessesResponse)(nil),   // 11: agentsessions.v1.ListHarnessesResponse
	(*RetireHarnessRequest)(nil),    // 12: agentsessions.v1.RetireHarnessRequest
	(*Capabilities)(nil),            // 13: agentsessions.v1.Capabilities
	(*ResourceMetadata)(nil),        // 14: agentsessions.v1.ResourceMetadata
	(*timestamppb.Timestamp)(nil),   // 15: google.protobuf.Timestamp
	(*HarnessDescriptor)(nil),       // 16: agentsessions.v1.HarnessDescriptor
}
var file_harness_registry_proto_depIdxs = []int32{
	3,  // 0: agentsessions.v1.HarnessSpec.remote:type_name -> agentsessions.v1.RemotePlacement
	4,  // 1: agentsessions.v1.HarnessSpec.substrate:type_name -> agentsessions.v1.SubstratePlacement
	13, // 2: agentsessions.v1.HarnessSpec.capabilities:type_name -> agentsessions.v1.Capabilities
	14, // 3: agentsessions.v1.HarnessRegistration.metadata:type_name -> agentsessions.v1.ResourceMetadata
	5,  // 4: agentsessions.v1.HarnessRegistration.spec:type_name -> agentsessions.v1.HarnessSpec
	0,  // 5: agentsessions.v1.HarnessRegistration.state:type_name -> agentsessions.v1.HarnessState
	1,  // 6: agentsessions.v1.HarnessRegistration.source:type_name -> agentsessions.v1.HarnessSource
	15, // 7: agentsessions.v1.HarnessRegistration.retire_time:type_name -> google.protobuf.Timestamp
	16, // 8: agentsessions.v1.HarnessRegistration.observed:type_name -> agentsessions.v1.HarnessDescriptor
	5,  // 9: agentsessions.v1.RegisterHarnessRequest.spec:type_name -> agentsessions.v1.HarnessSpec
	6,  // 10: agentsessions.v1.RegisterHarnessResponse.harness:type_name -> agentsessions.v1.HarnessRegistration
	2,  // 11: agentsessions.v1.RegisterHarnessResponse.outcome:type_name -> agentsessions.v1.RegisterOutcome
	6,  // 12: agentsessions.v1.ListHarnessesResponse.harnesses:type_name -> agentsessions.v1.HarnessRegistration
	7,  // 13: agentsessions.v1.HarnessRegistry.RegisterHarness:input_type -> agentsessions.v1.RegisterHarnessRequest
	9,  // 14: agentsessions.v1.HarnessRegistry.GetHarness:input_type -> agentsessions.v1.GetHarnessRequest
	10, // 15: agentsessions.v1.HarnessRegistry.ListHarnesses:input_type -> agentsessions.v1.ListHarnessesRequest
	12, // 16: agentsessions.v1.HarnessRegistry.RetireHarness:input_type -> agentsessions.v1.RetireHarnessRequest
	8,  // 17: agentsessions.v1.HarnessRegistry.RegisterHarness:output_type -> agentsessions.v1.RegisterHarnessResponse
	6,  // 18: agentsessions.v1.HarnessRegistry.GetHarness:output_type -> agentsessions.v1.HarnessRegistration
	11, // 19: agentsessions.v1.HarnessRegistry.ListHarnesses:output_type -> agentsessions.v1.ListHarnessesResponse
	6,  // 20: agentsessions.v1.HarnessRegistry.RetireHarness:output_type -> agentsessions.v1.HarnessRegistration
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_harness_registry_proto_init() }
func file_harness_registry_proto_init() {
	if File_harness_registry_proto != nil {
		return
	}
	file_common_proto_init()
	file_harness_proto_init()
	file_harness_registry_proto_msgTypes[2].OneofWrappers = []any{
		(*HarnessSpec_Remote)(nil),
		(*HarnessSpec_Substrate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_harness_registry_proto_rawDesc), len(file_harness_registry_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_harness_registry_proto_goTypes,
		DependencyIndexes: file_harness_registry_proto_depIdxs,
		EnumInfos:         file_harness_registry_proto_enumTypes,
		MessageInfos:      file_harness_registry_proto_msgTypes,
	}.Build()
	File_harness_registry_proto = out.File
	file_harness_registry_proto_goTypes = nil
	file_harness_registry_proto_depIdxs = nil
}
