// The HarnessRegistry admin API: register, inspect and retire harnesses on a running host.
//
// A registration is immutable. Its spec is content-addressed by spec_digest, so registering the
// same spec under the same name again changes nothing, and a different spec under a taken name is
// refused. Retiring a harness refuses new sessions on it while every existing session keeps
// running, resuming and forking. Registering the identical spec again reactivates it.
//
// This service decides what the host dials and pays model calls for, so it is an operator
// surface, not a client one. agentsessionsd serves it only on a separate optional literal-loopback
// listener (-registry-addr); Sessions never serves this API. Both listeners are plaintext and
// unauthenticated. Every local or same-pod process that can reach the operator port can administer
// registrations. See docs/security.md.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: harness_registry.proto

package agentsessionsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HarnessRegistry_RegisterHarness_FullMethodName = "/agentsessions.v1.HarnessRegistry/RegisterHarness"
	HarnessRegistry_GetHarness_FullMethodName      = "/agentsessions.v1.HarnessRegistry/GetHarness"
	HarnessRegistry_ListHarnesses_FullMethodName   = "/agentsessions.v1.HarnessRegistry/ListHarnesses"
	HarnessRegistry_RetireHarness_FullMethodName   = "/agentsessions.v1.HarnessRegistry/RetireHarness"
)

// HarnessRegistryClient is the client API for HarnessRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HarnessRegistry manages the harnesses a host can place sessions on. It is an admin API: a caller
// that can register a harness decides where the host sends session history and whose model calls it
// pays for. agentsessionsd serves this service only when -registry-addr is set to a literal loopback
// IP:port (for example 127.0.0.1:8081), on a separate gRPC server from Sessions. There is no TLS or
// authentication on either listener. Any process that can reach this port can administer it.
//
// CLI usage (pass --server on every operator command; no embedded registry):
//
// ```sh
// agentctl harness register --server 127.0.0.1:8081 --name mine --spec spec.json
// agentctl harness get --server 127.0.0.1:8081 --name mine --observe
// agentctl harness list --server 127.0.0.1:8081 --include-retired --page-size 50
// agentctl harness retire --server 127.0.0.1:8081 --name mine --reason maintenance
// ```
//
// spec.json is strict HarnessSpec proto-JSON, for example:
//
// ```json
// {"remote":{"address":"127.0.0.1:9000"},"capabilities":{"resumability":"RESUMABILITY_STATELESS_REPLAY"},"descriptor_id":"echo"}
// ```
//
// Remote registrations require agentsessionsd -model; substrate placements are not supported by
// this daemon. The CLI prints the full proto-JSON response, including digest and lifecycle state.
type HarnessRegistryClient interface {
	// Returns CREATED, UNCHANGED or REACTIVATED. ALREADY_EXISTS when the name holds a different spec,
	// or is taken by or reserved for a STATIC harness. FAILED_PRECONDITION when the host cannot serve
	// the placement.
	RegisterHarness(ctx context.Context, in *RegisterHarnessRequest, opts ...grpc.CallOption) (*RegisterHarnessResponse, error)
	// NOT_FOUND for a name that is neither STATIC nor registered.
	GetHarness(ctx context.Context, in *GetHarnessRequest, opts ...grpc.CallOption) (*HarnessRegistration, error)
	ListHarnesses(ctx context.Context, in *ListHarnessesRequest, opts ...grpc.CallOption) (*ListHarnessesResponse, error)
	// Idempotent: retiring a RETIRED harness returns it unchanged. FAILED_PRECONDITION for a STATIC
	// harness; NOT_FOUND for an unknown name.
	RetireHarness(ctx context.Context, in *RetireHarnessRequest, opts ...grpc.CallOption) (*HarnessRegistration, error)
}

type harnessRegistryClient struct {
	cc grpc.ClientConnInterface
}

func NewHarnessRegistryClient(cc grpc.ClientConnInterface) HarnessRegistryClient {
	return &harnessRegistryClient{cc}
}

func (c *harnessRegistryClient) RegisterHarness(ctx context.Context, in *RegisterHarnessRequest, opts ...grpc.CallOption) (*RegisterHarnessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterHarnessResponse)
	err := c.cc.Invoke(ctx, HarnessRegistry_RegisterHarness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harnessRegistryClient) GetHarness(ctx context.Context, in *GetHarnessRequest, opts ...grpc.CallOption) (*HarnessRegistration, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HarnessRegistration)
	err := c.cc.Invoke(ctx, HarnessRegistry_GetHarness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harnessRegistryClient) ListHarnesses(ctx context.Context, in *ListHarnessesRequest, opts ...grpc.CallOption) (*ListHarnessesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHarnessesResponse)
	err := c.cc.Invoke(ctx, HarnessRegistry_ListHarnesses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harnessRegistryClient) RetireHarness(ctx context.Context, in *RetireHarnessRequest, opts ...grpc.CallOption) (*HarnessRegistration, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HarnessRegistration)
	err := c.cc.Invoke(ctx, HarnessRegistry_RetireHarness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HarnessRegistryServer is the server API for HarnessRegistry service.
// All implementations must embed UnimplementedHarnessRegistryServer
// for forward compatibility.
//
// HarnessRegistry manages the harnesses a host can place sessions on. It is an admin API: a caller
// that can register a harness decides where the host sends session history and whose model calls it
// pays for. agentsessionsd serves this service only when -registry-addr is set to a literal loopback
// IP:port (for example 127.0.0.1:8081), on a separate gRPC server from Sessions. There is no TLS or
// authentication on either listener. Any process that can reach this port can administer it.
//
// CLI usage (pass --server on every operator command; no embedded registry):
//
// ```sh
// agentctl harness register --server 127.0.0.1:8081 --name mine --spec spec.json
// agentctl harness get --server 127.0.0.1:8081 --name mine --observe
// agentctl harness list --server 127.0.0.1:8081 --include-retired --page-size 50
// agentctl harness retire --server 127.0.0.1:8081 --name mine --reason maintenance
// ```
//
// spec.json is strict HarnessSpec proto-JSON, for example:
//
// ```json
// {"remote":{"address":"127.0.0.1:9000"},"capabilities":{"resumability":"RESUMABILITY_STATELESS_REPLAY"},"descriptor_id":"echo"}
// ```
//
// Remote registrations require agentsessionsd -model; substrate placements are not supported by
// this daemon. The CLI prints the full proto-JSON response, including digest and lifecycle state.
type HarnessRegistryServer interface {
	// Returns CREATED, UNCHANGED or REACTIVATED. ALREADY_EXISTS when the name holds a different spec,
	// or is taken by or reserved for a STATIC harness. FAILED_PRECONDITION when the host cannot serve
	// the placement.
	RegisterHarness(context.Context, *RegisterHarnessRequest) (*RegisterHarnessResponse, error)
	// NOT_FOUND for a name that is neither STATIC nor registered.
	GetHarness(context.Context, *GetHarnessRequest) (*HarnessRegistration, error)
	ListHarnesses(context.Context, *ListHarnessesRequest) (*ListHarnessesResponse, error)
	// Idempotent: retiring a RETIRED harness returns it unchanged. FAILED_PRECONDITION for a STATIC
	// harness; NOT_FOUND for an unknown name.
	RetireHarness(context.Context, *RetireHarnessRequest) (*HarnessRegistration, error)
	mustEmbedUnimplementedHarnessRegistryServer()
}

// UnimplementedHarnessRegistryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHarnessRegistryServer struct{}

func (UnimplementedHarnessRegistryServer) RegisterHarness(context.Context, *RegisterHarnessRequest) (*RegisterHarnessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterHarness not implemented")
}
func (UnimplementedHarnessRegistryServer) GetHarness(context.Context, *GetHarnessRequest) (*HarnessRegistration, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHarness not implemented")
}
func (UnimplementedHarnessRegistryServer) ListHarnesses(context.Context, *ListHarnessesRequest) (*ListHarnessesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHarnesses not implemented")
}
func (UnimplementedHarnessRegistryServer) RetireHarness(context.Context, *RetireHarnessRequest) (*HarnessRegistration, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetireHarness not implemented")
}
func (UnimplementedHarnessRegistryServer) mustEmbedUnimplementedHarnessRegistryServer() {}
func (UnimplementedHarnessRegistryServer) testEmbeddedByValue()                         {}

// UnsafeHarnessRegistryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HarnessRegistryServer will
// result in compilation errors.
type UnsafeHarnessRegistryServer interface {
	mustEmbedUnimplementedHarnessRegistryServer()
}

func RegisterHarnessRegistryServer(s grpc.ServiceRegistrar, srv HarnessRegistryServer) {
	// If the following call pancis, it indicates UnimplementedHarnessRegistryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HarnessRegistry_ServiceDesc, srv)
}

func _HarnessRegistry_RegisterHarness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterHarnessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarnessRegistryServer).RegisterHarness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HarnessRegistry_RegisterHarness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarnessRegistryServer).RegisterHarness(ctx, req.(*RegisterHarnessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarnessRegistry_GetHarness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHarnessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarnessRegistryServer).GetHarness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HarnessRegistry_GetHarness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarnessRegistryServer).GetHarness(ctx, req.(*GetHarnessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarnessRegistry_ListHarnesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHarnessesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarnessRegistryServer).ListHarnesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HarnessRegistry_ListHarnesses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarnessRegistryServer).ListHarnesses(ctx, req.(*ListHarnessesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HarnessRegistry_RetireHarness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetireHarnessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarnessRegistryServer).RetireHarness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HarnessRegistry_RetireHarness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarnessRegistryServer).RetireHarness(ctx, req.(*RetireHarnessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HarnessRegistry_ServiceDesc is the grpc.ServiceDesc for HarnessRegistry service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HarnessRegistry_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentsessions.v1.HarnessRegistry",
	HandlerType: (*HarnessRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterHarness",
			Handler:    _HarnessRegistry_RegisterHarness_Handler,
		},
		{
			MethodName: "GetHarness",
			Handler:    _HarnessRegistry_GetHarness_Handler,
		},
		{
			MethodName: "ListHarnesses",
			Handler:    _HarnessRegistry_ListHarnesses_Handler,
		},
		{
			MethodName: "RetireHarness",
			Handler:    _HarnessRegistry_RetireHarness_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "harness_registry.proto",
}
