// The Harness BYOH SPI: the contract between the host and an agent implementation.
//
// A Microsoft Agent Framework (MAF) agent, a GitHub Copilot agent, or a custom agent
// implements it via a thin adapter. The host drives one execution per Connect stream;
// the harness streams typed Events terminated by one EVENT_END. Beyond plain streaming, it
// adds tool-call / approval mediation, per-call usage, and capability declaration.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: harness.proto

package agentsessionsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Harness_Describe_FullMethodName = "/agentsessions.v1.Harness/Describe"
	Harness_Connect_FullMethodName  = "/agentsessions.v1.Harness/Connect"
)

// HarnessClient is the client API for Harness service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HarnessClient interface {
	// Describe returns the static contract; used to match the harness to a runtime.
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*HarnessDescriptor, error)
	// Connect drives ONE execution. The host sends Start (and optional control frames);
	// the harness streams Events terminated by exactly one EVENT_END.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControllerFrame, Event], error)
}

type harnessClient struct {
	cc grpc.ClientConnInterface
}

func NewHarnessClient(cc grpc.ClientConnInterface) HarnessClient {
	return &harnessClient{cc}
}

func (c *harnessClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*HarnessDescriptor, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HarnessDescriptor)
	err := c.cc.Invoke(ctx, Harness_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *harnessClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControllerFrame, Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Harness_ServiceDesc.Streams[0], Harness_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ControllerFrame, Event]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Harness_ConnectClient = grpc.BidiStreamingClient[ControllerFrame, Event]

// HarnessServer is the server API for Harness service.
// All implementations must embed UnimplementedHarnessServer
// for forward compatibility.
type HarnessServer interface {
	// Describe returns the static contract; used to match the harness to a runtime.
	Describe(context.Context, *DescribeRequest) (*HarnessDescriptor, error)
	// Connect drives ONE execution. The host sends Start (and optional control frames);
	// the harness streams Events terminated by exactly one EVENT_END.
	Connect(grpc.BidiStreamingServer[ControllerFrame, Event]) error
	mustEmbedUnimplementedHarnessServer()
}

// UnimplementedHarnessServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHarnessServer struct{}

func (UnimplementedHarnessServer) Describe(context.Context, *DescribeRequest) (*HarnessDescriptor, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedHarnessServer) Connect(grpc.BidiStreamingServer[ControllerFrame, Event]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedHarnessServer) mustEmbedUnimplementedHarnessServer() {}
func (UnimplementedHarnessServer) testEmbeddedByValue()                 {}

// UnsafeHarnessServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HarnessServer will
// result in compilation errors.
type UnsafeHarnessServer interface {
	mustEmbedUnimplementedHarnessServer()
}

func RegisterHarnessServer(s grpc.ServiceRegistrar, srv HarnessServer) {
	// If the following call pancis, it indicates UnimplementedHarnessServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Harness_ServiceDesc, srv)
}

func _Harness_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HarnessServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Harness_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HarnessServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Harness_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HarnessServer).Connect(&grpc.GenericServerStream[ControllerFrame, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Harness_ConnectServer = grpc.BidiStreamingServer[ControllerFrame, Event]

// Harness_ServiceDesc is the grpc.ServiceDesc for Harness service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Harness_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentsessions.v1.Harness",
	HandlerType: (*HarnessServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _Harness_Describe_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _Harness_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "harness.proto",
}
