// The Sessions control-plane API (client-facing) and the Runtime compute types.
//
// A Session is a durable conversation (event log) plus zero-or-one live incarnation.
// Each Exec is one execution/turn. Fork branches the log at a sequence.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: session.proto

package agentsessionsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Phase flattens two axes — execution (the log) and compute (the incarnation) — into a
// single lifecycle enum.
type Phase int32

const (
	Phase_PHASE_UNSPECIFIED Phase = 0
	Phase_PHASE_PENDING     Phase = 1
	Phase_PHASE_RUNNING     Phase = 2
	Phase_PHASE_PAUSING     Phase = 3
	Phase_PHASE_PAUSED      Phase = 4 // warm: resident, worker held
	Phase_PHASE_SUSPENDING  Phase = 5
	Phase_PHASE_SUSPENDED   Phase = 6 // cold: snapshot in storage, worker freed
	Phase_PHASE_RESUMING    Phase = 7
	Phase_PHASE_FORKING     Phase = 8
	Phase_PHASE_TERMINATED  Phase = 9 // log retained + replayable
	Phase_PHASE_FAILED      Phase = 10
)

// Enum value maps for Phase.
var (
	Phase_name = map[int32]string{
		0:  "PHASE_UNSPECIFIED",
		1:  "PHASE_PENDING",
		2:  "PHASE_RUNNING",
		3:  "PHASE_PAUSING",
		4:  "PHASE_PAUSED",
		5:  "PHASE_SUSPENDING",
		6:  "PHASE_SUSPENDED",
		7:  "PHASE_RESUMING",
		8:  "PHASE_FORKING",
		9:  "PHASE_TERMINATED",
		10: "PHASE_FAILED",
	}
	Phase_value = map[string]int32{
		"PHASE_UNSPECIFIED": 0,
		"PHASE_PENDING":     1,
		"PHASE_RUNNING":     2,
		"PHASE_PAUSING":     3,
		"PHASE_PAUSED":      4,
		"PHASE_SUSPENDING":  5,
		"PHASE_SUSPENDED":   6,
		"PHASE_RESUMING":    7,
		"PHASE_FORKING":     8,
		"PHASE_TERMINATED":  9,
		"PHASE_FAILED":      10,
	}
)

func (x Phase) Enum() *Phase {
	p := new(Phase)
	*p = x
	return p
}

func (x Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_session_proto_enumTypes[0].Descriptor()
}

func (Phase) Type() protoreflect.EnumType {
	return &file_session_proto_enumTypes[0]
}

func (x Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Phase.Descriptor instead.
func (Phase) EnumDescriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{0}
}

// ExecState is the execution/turn axis; ComputeState is the incarnation axis. The two are
// modeled explicitly (§6 of the replay contract); Phase above is a derived summary.
type ExecState int32

const (
	ExecState_EXEC_STATE_UNSPECIFIED ExecState = 0
	ExecState_EXEC_PENDING           ExecState = 1
	ExecState_EXEC_RUNNING           ExecState = 2
	ExecState_EXEC_AWAITING          ExecState = 3 // blocked on approval/input, resolved from the log
	ExecState_EXEC_COMPLETED         ExecState = 4
	ExecState_EXEC_FAILED            ExecState = 5
	ExecState_EXEC_CANCELED          ExecState = 6
)

// Enum value maps for ExecState.
var (
	ExecState_name = map[int32]string{
		0: "EXEC_STATE_UNSPECIFIED",
		1: "EXEC_PENDING",
		2: "EXEC_RUNNING",
		3: "EXEC_AWAITING",
		4: "EXEC_COMPLETED",
		5: "EXEC_FAILED",
		6: "EXEC_CANCELED",
	}
	ExecState_value = map[string]int32{
		"EXEC_STATE_UNSPECIFIED": 0,
		"EXEC_PENDING":           1,
		"EXEC_RUNNING":           2,
		"EXEC_AWAITING":          3,
		"EXEC_COMPLETED":         4,
		"EXEC_FAILED":            5,
		"EXEC_CANCELED":          6,
	}
)

func (x ExecState) Enum() *ExecState {
	p := new(ExecState)
	*p = x
	return p
}

func (x ExecState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecState) Descriptor() protoreflect.EnumDescriptor {
	return file_session_proto_enumTypes[1].Descriptor()
}

func (ExecState) Type() protoreflect.EnumType {
	return &file_session_proto_enumTypes[1]
}

func (x ExecState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecState.Descriptor instead.
func (ExecState) EnumDescriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{1}
}

type ComputeState int32

const (
	ComputeState_COMPUTE_STATE_UNSPECIFIED ComputeState = 0
	ComputeState_COMPUTE_NONE              ComputeState = 1 // no incarnation
	ComputeState_COMPUTE_LIVE              ComputeState = 2
	ComputeState_COMPUTE_WARM              ComputeState = 3 // paused: resident, worker held
	ComputeState_COMPUTE_COLD              ComputeState = 4 // suspended: snapshot in storage, worker freed
	ComputeState_COMPUTE_TERMINATED        ComputeState = 5
)

// Enum value maps for ComputeState.
var (
	ComputeState_name = map[int32]string{
		0: "COMPUTE_STATE_UNSPECIFIED",
		1: "COMPUTE_NONE",
		2: "COMPUTE_LIVE",
		3: "COMPUTE_WARM",
		4: "COMPUTE_COLD",
		5: "COMPUTE_TERMINATED",
	}
	ComputeState_value = map[string]int32{
		"COMPUTE_STATE_UNSPECIFIED": 0,
		"COMPUTE_NONE":              1,
		"COMPUTE_LIVE":              2,
		"COMPUTE_WARM":              3,
		"COMPUTE_COLD":              4,
		"COMPUTE_TERMINATED":        5,
	}
)

func (x ComputeState) Enum() *ComputeState {
	p := new(ComputeState)
	*p = x
	return p
}

func (x ComputeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComputeState) Descriptor() protoreflect.EnumDescriptor {
	return file_session_proto_enumTypes[2].Descriptor()
}

func (ComputeState) Type() protoreflect.EnumType {
	return &file_session_proto_enumTypes[2]
}

func (x ComputeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ComputeState.Descriptor instead.
func (ComputeState) EnumDescriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{2}
}

// SnapshotRef is the session-STATUS ref carried in ComputeRef below. It is NOT yet wired in Go (no
// converter). The canonical wired form is api.SnapshotRef, and the durable log carries the ref inline
// on the SUSPEND Lifecycle event (common.proto Lifecycle.snapshot_*). The oneof here cannot hold both
// local AND external_uri, which a substrate ref needs.
// TODO(spike): flatten this oneof to match api.SnapshotRef when ComputeRef/substrate status is wired.
// An in-place flatten is buf-breaking (oneof-exit is flagged even under WIRE_JSON), so it needs a
// coordinated schema version bump, not an edit.
type SnapshotRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Loc:
	//
	//	*SnapshotRef_Local
	//	*SnapshotRef_ExternalUri
	Loc           isSnapshotRef_Loc `protobuf_oneof:"loc"`
	Memory        bool              `protobuf:"varint,3,opt,name=memory,proto3" json:"memory,omitempty"` // RAM/process captured? pod: false, kata/clh: true
	Sealed        bool              `protobuf:"varint,4,opt,name=sealed,proto3" json:"sealed,omitempty"` // encrypted + attested (confidential)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRef) Reset() {
	*x = SnapshotRef{}
	mi := &file_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRef) ProtoMessage() {}

func (x *SnapshotRef) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRef.ProtoReflect.Descriptor instead.
func (*SnapshotRef) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{0}
}

func (x *SnapshotRef) GetLoc() isSnapshotRef_Loc {
	if x != nil {
		return x.Loc
	}
	return nil
}

func (x *SnapshotRef) GetLocal() string {
	if x != nil {
		if x, ok := x.Loc.(*SnapshotRef_Local); ok {
			return x.Local
		}
	}
	return ""
}

func (x *SnapshotRef) GetExternalUri() string {
	if x != nil {
		if x, ok := x.Loc.(*SnapshotRef_ExternalUri); ok {
			return x.ExternalUri
		}
	}
	return ""
}

func (x *SnapshotRef) GetMemory() bool {
	if x != nil {
		return x.Memory
	}
	return false
}

func (x *SnapshotRef) GetSealed() bool {
	if x != nil {
		return x.Sealed
	}
	return false
}

type isSnapshotRef_Loc interface {
	isSnapshotRef_Loc()
}

type SnapshotRef_Local struct {
	Local string `protobuf:"bytes,1,opt,name=local,proto3,oneof"`
}

type SnapshotRef_ExternalUri struct {
	ExternalUri string `protobuf:"bytes,2,opt,name=external_uri,json=externalUri,proto3,oneof"`
}

func (*SnapshotRef_Local) isSnapshotRef_Loc() {}

func (*SnapshotRef_ExternalUri) isSnapshotRef_Loc() {}

type RuntimeCapabilities struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MemorySnapshot bool                   `protobuf:"varint,1,opt,name=memory_snapshot,json=memorySnapshot,proto3" json:"memory_snapshot,omitempty"`
	CowFork        bool                   `protobuf:"varint,2,opt,name=cow_fork,json=cowFork,proto3" json:"cow_fork,omitempty"`
	Attest         bool                   `protobuf:"varint,3,opt,name=attest,proto3" json:"attest,omitempty"`
	GpuState       bool                   `protobuf:"varint,4,opt,name=gpu_state,json=gpuState,proto3" json:"gpu_state,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RuntimeCapabilities) Reset() {
	*x = RuntimeCapabilities{}
	mi := &file_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeCapabilities) ProtoMessage() {}

func (x *RuntimeCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeCapabilities.ProtoReflect.Descriptor instead.
func (*RuntimeCapabilities) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{1}
}

func (x *RuntimeCapabilities) GetMemorySnapshot() bool {
	if x != nil {
		return x.MemorySnapshot
	}
	return false
}

func (x *RuntimeCapabilities) GetCowFork() bool {
	if x != nil {
		return x.CowFork
	}
	return false
}

func (x *RuntimeCapabilities) GetAttest() bool {
	if x != nil {
		return x.Attest
	}
	return false
}

func (x *RuntimeCapabilities) GetGpuState() bool {
	if x != nil {
		return x.GpuState
	}
	return false
}

type ComputeRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runtime       string                 `protobuf:"bytes,1,opt,name=runtime,proto3" json:"runtime,omitempty"` // "pod" | "kata" | "clh" | "substrate"
	Worker        string                 `protobuf:"bytes,2,opt,name=worker,proto3" json:"worker,omitempty"`   // pod/worker id when live/warm; empty when cold
	Snapshot      *SnapshotRef           `protobuf:"bytes,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Capabilities  *RuntimeCapabilities   `protobuf:"bytes,4,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // backend-specific, e.g. substrate actor/atespace
	FenceToken    int64                  `protobuf:"varint,6,opt,name=fence_token,json=fenceToken,proto3" json:"fence_token,omitempty"`                                                        // monotonic; log rejects appends from a superseded incarnation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeRef) Reset() {
	*x = ComputeRef{}
	mi := &file_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeRef) ProtoMessage() {}

func (x *ComputeRef) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeRef.ProtoReflect.Descriptor instead.
func (*ComputeRef) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{2}
}

func (x *ComputeRef) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *ComputeRef) GetWorker() string {
	if x != nil {
		return x.Worker
	}
	return ""
}

func (x *ComputeRef) GetSnapshot() *SnapshotRef {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *ComputeRef) GetCapabilities() *RuntimeCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ComputeRef) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ComputeRef) GetFenceToken() int64 {
	if x != nil {
		return x.FenceToken
	}
	return 0
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *ResourceMetadata      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Harness       string                 `protobuf:"bytes,2,opt,name=harness,proto3" json:"harness,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`                                                                        // model-agnostic id
	ExecState     ExecState              `protobuf:"varint,13,opt,name=exec_state,json=execState,proto3,enum=agentsessions.v1.ExecState" json:"exec_state,omitempty"`             // execution/turn axis
	ComputeState  ComputeState           `protobuf:"varint,14,opt,name=compute_state,json=computeState,proto3,enum=agentsessions.v1.ComputeState" json:"compute_state,omitempty"` // incarnation axis
	LastSeq       int64                  `protobuf:"varint,5,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`                                                    // event-log cursor
	ParentUid     string                 `protobuf:"bytes,6,opt,name=parent_uid,json=parentUid,proto3" json:"parent_uid,omitempty"`                                               // fork lineage
	ForkSeq       int64                  `protobuf:"varint,7,opt,name=fork_seq,json=forkSeq,proto3" json:"fork_seq,omitempty"`
	Identity      *IdentityRef           `protobuf:"bytes,8,opt,name=identity,proto3" json:"identity,omitempty"`
	Compute       *ComputeRef            `protobuf:"bytes,9,opt,name=compute,proto3" json:"compute,omitempty"` // empty when SUSPENDED/TERMINATED
	Origin        *Origin                `protobuf:"bytes,10,opt,name=origin,proto3" json:"origin,omitempty"`  // neutral external context; filled by a producer adapter
	Labels        map[string]string      `protobuf:"bytes,11,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations   map[string]string      `protobuf:"bytes,12,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // free-form adapter metadata (K8s-style)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{3}
}

func (x *Session) GetMetadata() *ResourceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Session) GetHarness() string {
	if x != nil {
		return x.Harness
	}
	return ""
}

func (x *Session) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Session) GetExecState() ExecState {
	if x != nil {
		return x.ExecState
	}
	return ExecState_EXEC_STATE_UNSPECIFIED
}

func (x *Session) GetComputeState() ComputeState {
	if x != nil {
		return x.ComputeState
	}
	return ComputeState_COMPUTE_STATE_UNSPECIFIED
}

func (x *Session) GetLastSeq() int64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *Session) GetParentUid() string {
	if x != nil {
		return x.ParentUid
	}
	return ""
}

func (x *Session) GetForkSeq() int64 {
	if x != nil {
		return x.ForkSeq
	}
	return 0
}

func (x *Session) GetIdentity() *IdentityRef {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *Session) GetCompute() *ComputeRef {
	if x != nil {
		return x.Compute
	}
	return nil
}

func (x *Session) GetOrigin() *Origin {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *Session) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Session) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSessionRequest) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{5}
}

func (x *GetSessionRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{6}
}

func (x *ListSessionsRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{7}
}

func (x *ListSessionsResponse) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSessionRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type ExecRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Session string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	// Input messages for this turn. Empty = resume/re-drive the last non-terminal
	// execution with no new input (recovery after a crash/interruption).
	Inputs        []*Message `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	ResumeFromSeq int64      `protobuf:"varint,3,opt,name=resume_from_seq,json=resumeFromSeq,proto3" json:"resume_from_seq,omitempty"` // client replay cursor after a disconnect (was: last_seq)
	Harness       string     `protobuf:"bytes,4,opt,name=harness,proto3" json:"harness,omitempty"`                                     // empty = session default
	Config        []byte     `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	// Single-writer CAS: the host commits this execution's first event only if the log
	// head equals expected_last_seq. Mismatch is rejected (another writer advanced the log).
	ExpectedLastSeq int64 `protobuf:"varint,6,opt,name=expected_last_seq,json=expectedLastSeq,proto3" json:"expected_last_seq,omitempty"`
	DeadlineUnix    int64 `protobuf:"varint,7,opt,name=deadline_unix,json=deadlineUnix,proto3" json:"deadline_unix,omitempty"` // optional execution deadline (unix seconds); host cancels past it
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{9}
}

func (x *ExecRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *ExecRequest) GetInputs() []*Message {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *ExecRequest) GetResumeFromSeq() int64 {
	if x != nil {
		return x.ResumeFromSeq
	}
	return 0
}

func (x *ExecRequest) GetHarness() string {
	if x != nil {
		return x.Harness
	}
	return ""
}

func (x *ExecRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ExecRequest) GetExpectedLastSeq() int64 {
	if x != nil {
		return x.ExpectedLastSeq
	}
	return 0
}

func (x *ExecRequest) GetDeadlineUnix() int64 {
	if x != nil {
		return x.DeadlineUnix
	}
	return 0
}

type ReplayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	FromSeq       int64                  `protobuf:"varint,2,opt,name=from_seq,json=fromSeq,proto3" json:"from_seq,omitempty"`
	ToSeq         int64                  `protobuf:"varint,3,opt,name=to_seq,json=toSeq,proto3" json:"to_seq,omitempty"` // 0 = to head
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayRequest) Reset() {
	*x = ReplayRequest{}
	mi := &file_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayRequest) ProtoMessage() {}

func (x *ReplayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayRequest.ProtoReflect.Descriptor instead.
func (*ReplayRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{10}
}

func (x *ReplayRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *ReplayRequest) GetFromSeq() int64 {
	if x != nil {
		return x.FromSeq
	}
	return 0
}

func (x *ReplayRequest) GetToSeq() int64 {
	if x != nil {
		return x.ToSeq
	}
	return 0
}

type PauseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseRequest) Reset() {
	*x = PauseRequest{}
	mi := &file_session_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseRequest) ProtoMessage() {}

func (x *PauseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseRequest.ProtoReflect.Descriptor instead.
func (*PauseRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{11}
}

func (x *PauseRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

type SuspendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendRequest) Reset() {
	*x = SuspendRequest{}
	mi := &file_session_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendRequest) ProtoMessage() {}

func (x *SuspendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendRequest.ProtoReflect.Descriptor instead.
func (*SuspendRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{12}
}

func (x *SuspendRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

type ResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Boot          bool                   `protobuf:"varint,2,opt,name=boot,proto3" json:"boot,omitempty"` // true = cold-boot + replay instead of snapshot restore
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeRequest) Reset() {
	*x = ResumeRequest{}
	mi := &file_session_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeRequest) ProtoMessage() {}

func (x *ResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeRequest.ProtoReflect.Descriptor instead.
func (*ResumeRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{13}
}

func (x *ResumeRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *ResumeRequest) GetBoot() bool {
	if x != nil {
		return x.Boot
	}
	return false
}

type ForkRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Session string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	// 0 = HEAD. A REQUIRES_MEMORY_SNAPSHOT harness forks by cloning a memory snapshot, which captures
	// RAM as of now, so it accepts only HEAD; a historical seq is FAILED_PRECONDITION.
	AtSeq         int64             `protobuf:"varint,2,opt,name=at_seq,json=atSeq,proto3" json:"at_seq,omitempty"`
	Count         int32             `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`      // fan-out N children; must be 1..128, else INVALID_ARGUMENT
	Identity      *IdentityRef      `protobuf:"bytes,4,opt,name=identity,proto3" json:"identity,omitempty"` // optional child principal
	Labels        map[string]string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForkRequest) Reset() {
	*x = ForkRequest{}
	mi := &file_session_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkRequest) ProtoMessage() {}

func (x *ForkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkRequest.ProtoReflect.Descriptor instead.
func (*ForkRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{14}
}

func (x *ForkRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *ForkRequest) GetAtSeq() int64 {
	if x != nil {
		return x.AtSeq
	}
	return 0
}

func (x *ForkRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ForkRequest) GetIdentity() *IdentityRef {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *ForkRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ForkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Children      []*Session             `protobuf:"bytes,1,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForkResponse) Reset() {
	*x = ForkResponse{}
	mi := &file_session_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkResponse) ProtoMessage() {}

func (x *ForkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkResponse.ProtoReflect.Descriptor instead.
func (*ForkResponse) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{15}
}

func (x *ForkResponse) GetChildren() []*Session {
	if x != nil {
		return x.Children
	}
	return nil
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"` // USER | TIMEOUT | INTERNAL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_session_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{16}
}

func (x *CancelRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *CancelRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *CancelRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	ExecutionId   string                 `protobuf:"bytes,2,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_session_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{17}
}

func (x *HeartbeatRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *HeartbeatRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

// ExecUpdate is what the live Exec stream carries: a committed LogRecord, or an ephemeral
// streaming Delta (transport only — not logged, not hash-chained).
type ExecUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Update:
	//
	//	*ExecUpdate_Record
	//	*ExecUpdate_Delta
	Update        isExecUpdate_Update `protobuf_oneof:"update"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecUpdate) Reset() {
	*x = ExecUpdate{}
	mi := &file_session_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecUpdate) ProtoMessage() {}

func (x *ExecUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecUpdate.ProtoReflect.Descriptor instead.
func (*ExecUpdate) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{18}
}

func (x *ExecUpdate) GetUpdate() isExecUpdate_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *ExecUpdate) GetRecord() *LogRecord {
	if x != nil {
		if x, ok := x.Update.(*ExecUpdate_Record); ok {
			return x.Record
		}
	}
	return nil
}

func (x *ExecUpdate) GetDelta() *Delta {
	if x != nil {
		if x, ok := x.Update.(*ExecUpdate_Delta); ok {
			return x.Delta
		}
	}
	return nil
}

type isExecUpdate_Update interface {
	isExecUpdate_Update()
}

type ExecUpdate_Record struct {
	Record *LogRecord `protobuf:"bytes,1,opt,name=record,proto3,oneof"`
}

type ExecUpdate_Delta struct {
	Delta *Delta `protobuf:"bytes,2,opt,name=delta,proto3,oneof"`
}

func (*ExecUpdate_Record) isExecUpdate_Update() {}

func (*ExecUpdate_Delta) isExecUpdate_Update() {}

// Delta is an ephemeral streaming chunk that coalesces into a finalized EVENT_OUTPUT (or
// reasoning) part. No seq; never hash-chained (§8, A2A TaskArtifactUpdateEvent).
type Delta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	PartIndex     int32                  `protobuf:"varint,2,opt,name=part_index,json=partIndex,proto3" json:"part_index,omitempty"` // which content part it accumulates into
	Chunk         string                 `protobuf:"bytes,3,opt,name=chunk,proto3" json:"chunk,omitempty"`                           // text chunk; binary/media deltas are a later addition
	Done          bool                   `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"`                            // last delta for this part
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delta) Reset() {
	*x = Delta{}
	mi := &file_session_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delta) ProtoMessage() {}

func (x *Delta) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delta.ProtoReflect.Descriptor instead.
func (*Delta) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{19}
}

func (x *Delta) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *Delta) GetPartIndex() int32 {
	if x != nil {
		return x.PartIndex
	}
	return 0
}

func (x *Delta) GetChunk() string {
	if x != nil {
		return x.Chunk
	}
	return ""
}

func (x *Delta) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

var File_session_proto protoreflect.FileDescriptor

const file_session_proto_rawDesc = "" +
	"\n" +
	"\rsession.proto\x12\x10agentsessions.v1\x1a\fcommon.proto\"\x81\x01\n" +
	"\vSnapshotRef\x12\x16\n" +
	"\x05local\x18\x01 \x01(\tH\x00R\x05local\x12#\n" +
	"\fexternal_uri\x18\x02 \x01(\tH\x00R\vexternalUri\x12\x16\n" +
	"\x06memory\x18\x03 \x01(\bR\x06memory\x12\x16\n" +
	"\x06sealed\x18\x04 \x01(\bR\x06sealedB\x05\n" +
	"\x03loc\"\x8e\x01\n" +
	"\x13RuntimeCapabilities\x12'\n" +
	"\x0fmemory_snapshot\x18\x01 \x01(\bR\x0ememorySnapshot\x12\x19\n" +
	"\bcow_fork\x18\x02 \x01(\bR\acowFork\x12\x16\n" +
	"\x06attest\x18\x03 \x01(\bR\x06attest\x12\x1b\n" +
	"\tgpu_state\x18\x04 \x01(\bR\bgpuState\"\xf2\x02\n" +
	"\n" +
	"ComputeRef\x12\x18\n" +
	"\aruntime\x18\x01 \x01(\tR\aruntime\x12\x16\n" +
	"\x06worker\x18\x02 \x01(\tR\x06worker\x129\n" +
	"\bsnapshot\x18\x03 \x01(\v2\x1d.agentsessions.v1.SnapshotRefR\bsnapshot\x12I\n" +
	"\fcapabilities\x18\x04 \x01(\v2%.agentsessions.v1.RuntimeCapabilitiesR\fcapabilities\x12L\n" +
	"\n" +
	"attributes\x18\x05 \x03(\v2,.agentsessions.v1.ComputeRef.AttributesEntryR\n" +
	"attributes\x12\x1f\n" +
	"\vfence_token\x18\x06 \x01(\x03R\n" +
	"fenceToken\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x06\n" +
	"\aSession\x12>\n" +
	"\bmetadata\x18\x01 \x01(\v2\".agentsessions.v1.ResourceMetadataR\bmetadata\x12\x18\n" +
	"\aharness\x18\x02 \x01(\tR\aharness\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12:\n" +
	"\n" +
	"exec_state\x18\r \x01(\x0e2\x1b.agentsessions.v1.ExecStateR\texecState\x12C\n" +
	"\rcompute_state\x18\x0e \x01(\x0e2\x1e.agentsessions.v1.ComputeStateR\fcomputeState\x12\x19\n" +
	"\blast_seq\x18\x05 \x01(\x03R\alastSeq\x12\x1d\n" +
	"\n" +
	"parent_uid\x18\x06 \x01(\tR\tparentUid\x12\x19\n" +
	"\bfork_seq\x18\a \x01(\x03R\aforkSeq\x129\n" +
	"\bidentity\x18\b \x01(\v2\x1d.agentsessions.v1.IdentityRefR\bidentity\x126\n" +
	"\acompute\x18\t \x01(\v2\x1c.agentsessions.v1.ComputeRefR\acompute\x120\n" +
	"\x06origin\x18\n" +
	" \x01(\v2\x18.agentsessions.v1.OriginR\x06origin\x12=\n" +
	"\x06labels\x18\v \x03(\v2%.agentsessions.v1.Session.LabelsEntryR\x06labels\x12L\n" +
	"\vannotations\x18\f \x03(\v2*.agentsessions.v1.Session.AnnotationsEntryR\vannotations\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x04\x10\x05\"K\n" +
	"\x14CreateSessionRequest\x123\n" +
	"\asession\x18\x01 \x01(\v2\x19.agentsessions.v1.SessionR\asession\"%\n" +
	"\x11GetSessionRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"/\n" +
	"\x13ListSessionsRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\"M\n" +
	"\x14ListSessionsResponse\x125\n" +
	"\bsessions\x18\x01 \x03(\v2\x19.agentsessions.v1.SessionR\bsessions\"(\n" +
	"\x14DeleteSessionRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"\x85\x02\n" +
	"\vExecRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x121\n" +
	"\x06inputs\x18\x02 \x03(\v2\x19.agentsessions.v1.MessageR\x06inputs\x12&\n" +
	"\x0fresume_from_seq\x18\x03 \x01(\x03R\rresumeFromSeq\x12\x18\n" +
	"\aharness\x18\x04 \x01(\tR\aharness\x12\x16\n" +
	"\x06config\x18\x05 \x01(\fR\x06config\x12*\n" +
	"\x11expected_last_seq\x18\x06 \x01(\x03R\x0fexpectedLastSeq\x12#\n" +
	"\rdeadline_unix\x18\a \x01(\x03R\fdeadlineUnix\"[\n" +
	"\rReplayRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x12\x19\n" +
	"\bfrom_seq\x18\x02 \x01(\x03R\afromSeq\x12\x15\n" +
	"\x06to_seq\x18\x03 \x01(\x03R\x05toSeq\"(\n" +
	"\fPauseRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\"*\n" +
	"\x0eSuspendRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\"=\n" +
	"\rResumeRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x12\x12\n" +
	"\x04boot\x18\x02 \x01(\bR\x04boot\"\x8d\x02\n" +
	"\vForkRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x12\x15\n" +
	"\x06at_seq\x18\x02 \x01(\x03R\x05atSeq\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x129\n" +
	"\bidentity\x18\x04 \x01(\v2\x1d.agentsessions.v1.IdentityRefR\bidentity\x12A\n" +
	"\x06labels\x18\x05 \x03(\v2).agentsessions.v1.ForkRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	"\fForkResponse\x125\n" +
	"\bchildren\x18\x01 \x03(\v2\x19.agentsessions.v1.SessionR\bchildren\"d\n" +
	"\rCancelRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"O\n" +
	"\x10HeartbeatRequest\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x12!\n" +
	"\fexecution_id\x18\x02 \x01(\tR\vexecutionId\"~\n" +
	"\n" +
	"ExecUpdate\x125\n" +
	"\x06record\x18\x01 \x01(\v2\x1b.agentsessions.v1.LogRecordH\x00R\x06record\x12/\n" +
	"\x05delta\x18\x02 \x01(\v2\x17.agentsessions.v1.DeltaH\x00R\x05deltaB\b\n" +
	"\x06update\"s\n" +
	"\x05Delta\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x1d\n" +
	"\n" +
	"part_index\x18\x02 \x01(\x05R\tpartIndex\x12\x14\n" +
	"\x05chunk\x18\x03 \x01(\tR\x05chunk\x12\x12\n" +
	"\x04done\x18\x04 \x01(\bR\x04done*\xe3\x01\n" +
	"\x05Phase\x12\x15\n" +
	"\x11PHASE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rPHASE_PENDING\x10\x01\x12\x11\n" +
	"\rPHASE_RUNNING\x10\x02\x12\x11\n" +
	"\rPHASE_PAUSING\x10\x03\x12\x10\n" +
	"\fPHASE_PAUSED\x10\x04\x12\x14\n" +
	"\x10PHASE_SUSPENDING\x10\x05\x12\x13\n" +
	"\x0fPHASE_SUSPENDED\x10\x06\x12\x12\n" +
	"\x0ePHASE_RESUMING\x10\a\x12\x11\n" +
	"\rPHASE_FORKING\x10\b\x12\x14\n" +
	"\x10PHASE_TERMINATED\x10\t\x12\x10\n" +
	"\fPHASE_FAILED\x10\n" +
	"*\x96\x01\n" +
	"\tExecState\x12\x1a\n" +
	"\x16EXEC_STATE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fEXEC_PENDING\x10\x01\x12\x10\n" +
	"\fEXEC_RUNNING\x10\x02\x12\x11\n" +
	"\rEXEC_AWAITING\x10\x03\x12\x12\n" +
	"\x0eEXEC_COMPLETED\x10\x04\x12\x0f\n" +
	"\vEXEC_FAILED\x10\x05\x12\x11\n" +
	"\rEXEC_CANCELED\x10\x06*\x8d\x01\n" +
	"\fComputeState\x12\x1d\n" +
	"\x19COMPUTE_STATE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fCOMPUTE_NONE\x10\x01\x12\x10\n" +
	"\fCOMPUTE_LIVE\x10\x02\x12\x10\n" +
	"\fCOMPUTE_WARM\x10\x03\x12\x10\n" +
	"\fCOMPUTE_COLD\x10\x04\x12\x16\n" +
	"\x12COMPUTE_TERMINATED\x10\x052\x9b\a\n" +
	"\bSessions\x12R\n" +
	"\rCreateSession\x12&.agentsessions.v1.CreateSessionRequest\x1a\x19.agentsessions.v1.Session\x12L\n" +
	"\n" +
	"GetSession\x12#.agentsessions.v1.GetSessionRequest\x1a\x19.agentsessions.v1.Session\x12]\n" +
	"\fListSessions\x12%.agentsessions.v1.ListSessionsRequest\x1a&.agentsessions.v1.ListSessionsResponse\x12R\n" +
	"\rDeleteSession\x12&.agentsessions.v1.DeleteSessionRequest\x1a\x19.agentsessions.v1.Session\x12E\n" +
	"\x04Exec\x12\x1d.agentsessions.v1.ExecRequest\x1a\x1c.agentsessions.v1.ExecUpdate0\x01\x12H\n" +
	"\x06Replay\x12\x1f.agentsessions.v1.ReplayRequest\x1a\x1b.agentsessions.v1.LogRecord0\x01\x12D\n" +
	"\x06Cancel\x12\x1f.agentsessions.v1.CancelRequest\x1a\x19.agentsessions.v1.Session\x12J\n" +
	"\tHeartbeat\x12\".agentsessions.v1.HeartbeatRequest\x1a\x19.agentsessions.v1.Session\x12B\n" +
	"\x05Pause\x12\x1e.agentsessions.v1.PauseRequest\x1a\x19.agentsessions.v1.Session\x12F\n" +
	"\aSuspend\x12 .agentsessions.v1.SuspendRequest\x1a\x19.agentsessions.v1.Session\x12D\n" +
	"\x06Resume\x12\x1f.agentsessions.v1.ResumeRequest\x1a\x19.agentsessions.v1.Session\x12E\n" +
	"\x04Fork\x12\x1d.agentsessions.v1.ForkRequest\x1a\x1e.agentsessions.v1.ForkResponseB<Z:github.com/aramase/agentsessions/api/genpb;agentsessionsv1b\x06proto3"

var (
	file_session_proto_rawDescOnce sync.Once
	file_session_proto_rawDescData []byte
)

func file_session_proto_rawDescGZIP() []byte {
	file_session_proto_rawDescOnce.Do(func() {
		file_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_session_proto_rawDesc), len(file_session_proto_rawDesc)))
	})
	return file_session_proto_rawDescData
}

var file_session_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_session_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_session_proto_goTypes = []any{
	(Phase)(0),                   // 0: agentsessions.v1.Phase
	(ExecState)(0),               // 1: agentsessions.v1.ExecState
	(ComputeState)(0),            // 2: agentsessions.v1.ComputeState
	(*SnapshotRef)(nil),          // 3: agentsessions.v1.SnapshotRef
	(*RuntimeCapabilities)(nil),  // 4: agentsessions.v1.RuntimeCapabilities
	(*ComputeRef)(nil),           // 5: agentsessions.v1.ComputeRef
	(*Session)(nil),              // 6: agentsessions.v1.Session
	(*CreateSessionRequest)(nil), // 7: agentsessions.v1.CreateSessionRequest
	(*GetSessionRequest)(nil),    // 8: agentsessions.v1.GetSessionRequest
	(*ListSessionsRequest)(nil),  // 9: agentsessions.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil), // 10: agentsessions.v1.ListSessionsResponse
	(*DeleteSessionRequest)(nil), // 11: agentsessions.v1.DeleteSessionRequest
	(*ExecRequest)(nil),          // 12: agentsessions.v1.ExecRequest
	(*ReplayRequest)(nil),        // 13: agentsessions.v1.ReplayRequest
	(*PauseRequest)(nil),         // 14: agentsessions.v1.PauseRequest
	(*SuspendRequest)(nil),       // 15: agentsessions.v1.SuspendRequest
	(*ResumeRequest)(nil),        // 16: agentsessions.v1.ResumeRequest
	(*ForkRequest)(nil),          // 17: agentsessions.v1.ForkRequest
	(*ForkResponse)(nil),         // 18: agentsessions.v1.ForkResponse
	(*CancelRequest)(nil),        // 19: agentsessions.v1.CancelRequest
	(*HeartbeatRequest)(nil),     // 20: agentsessions.v1.HeartbeatRequest
	(*ExecUpdate)(nil),           // 21: agentsessions.v1.ExecUpdate
	(*Delta)(nil),                // 22: agentsessions.v1.Delta
	nil,                          // 23: agentsessions.v1.ComputeRef.AttributesEntry
	nil,                          // 24: agentsessions.v1.Session.LabelsEntry
	nil,                          // 25: agentsessions.v1.Session.AnnotationsEntry
	nil,                          // 26: agentsessions.v1.ForkRequest.LabelsEntry
	(*ResourceMetadata)(nil),     // 27: agentsessions.v1.ResourceMetadata
	(*IdentityRef)(nil),          // 28: agentsessions.v1.IdentityRef
	(*Origin)(nil),               // 29: agentsessions.v1.Origin
	(*Message)(nil),              // 30: agentsessions.v1.Message
	(*LogRecord)(nil),            // 31: agentsessions.v1.LogRecord
}
var file_session_proto_depIdxs = []int32{
	3,  // 0: agentsessions.v1.ComputeRef.snapshot:type_name -> agentsessions.v1.SnapshotRef
	4,  // 1: agentsessions.v1.ComputeRef.capabilities:type_name -> agentsessions.v1.RuntimeCapabilities
	23, // 2: agentsessions.v1.ComputeRef.attributes:type_name -> agentsessions.v1.ComputeRef.AttributesEntry
	27, // 3: agentsessions.v1.Session.metadata:type_name -> agentsessions.v1.ResourceMetadata
	1,  // 4: agentsessions.v1.Session.exec_state:type_name -> agentsessions.v1.ExecState
	2,  // 5: agentsessions.v1.Session.compute_state:type_name -> agentsessions.v1.ComputeState
	28, // 6: agentsessions.v1.Session.identity:type_name -> agentsessions.v1.IdentityRef
	5,  // 7: agentsessions.v1.Session.compute:type_name -> agentsessions.v1.ComputeRef
	29, // 8: agentsessions.v1.Session.origin:type_name -> agentsessions.v1.Origin
	24, // 9: agentsessions.v1.Session.labels:type_name -> agentsessions.v1.Session.LabelsEntry
	25, // 10: agentsessions.v1.Session.annotations:type_name -> agentsessions.v1.Session.AnnotationsEntry
	6,  // 11: agentsessions.v1.CreateSessionRequest.session:type_name -> agentsessions.v1.Session
	6,  // 12: agentsessions.v1.ListSessionsResponse.sessions:type_name -> agentsessions.v1.Session
	30, // 13: agentsessions.v1.ExecRequest.inputs:type_name -> agentsessions.v1.Message
	28, // 14: agentsessions.v1.ForkRequest.identity:type_name -> agentsessions.v1.IdentityRef
	26, // 15: agentsessions.v1.ForkRequest.labels:type_name -> agentsessions.v1.ForkRequest.LabelsEntry
	6,  // 16: agentsessions.v1.ForkResponse.children:type_name -> agentsessions.v1.Session
	31, // 17: agentsessions.v1.ExecUpdate.record:type_name -> agentsessions.v1.LogRecord
	22, // 18: agentsessions.v1.ExecUpdate.delta:type_name -> agentsessions.v1.Delta
	7,  // 19: agentsessions.v1.Sessions.CreateSession:input_type -> agentsessions.v1.CreateSessionRequest
	8,  // 20: agentsessions.v1.Sessions.GetSession:input_type -> agentsessions.v1.GetSessionRequest
	9,  // 21: agentsessions.v1.Sessions.ListSessions:input_type -> agentsessions.v1.ListSessionsRequest
	11, // 22: agentsessions.v1.Sessions.DeleteSession:input_type -> agentsessions.v1.DeleteSessionRequest
	12, // 23: agentsessions.v1.Sessions.Exec:input_type -> agentsessions.v1.ExecRequest
	13, // 24: agentsessions.v1.Sessions.Replay:input_type -> agentsessions.v1.ReplayRequest
	19, // 25: agentsessions.v1.Sessions.Cancel:input_type -> agentsessions.v1.CancelRequest
	20, // 26: agentsessions.v1.Sessions.Heartbeat:input_type -> agentsessions.v1.HeartbeatRequest
	14, // 27: agentsessions.v1.Sessions.Pause:input_type -> agentsessions.v1.PauseRequest
	15, // 28: agentsessions.v1.Sessions.Suspend:input_type -> agentsessions.v1.SuspendRequest
	16, // 29: agentsessions.v1.Sessions.Resume:input_type -> agentsessions.v1.ResumeRequest
	17, // 30: agentsessions.v1.Sessions.Fork:input_type -> agentsessions.v1.ForkRequest
	6,  // 31: agentsessions.v1.Sessions.CreateSession:output_type -> agentsessions.v1.Session
	6,  // 32: agentsessions.v1.Sessions.GetSession:output_type -> agentsessions.v1.Session
	10, // 33: agentsessions.v1.Sessions.ListSessions:output_type -> agentsessions.v1.ListSessionsResponse
	6,  // 34: agentsessions.v1.Sessions.DeleteSession:output_type -> agentsessions.v1.Session
	21, // 35: agentsessions.v1.Sessions.Exec:output_type -> agentsessions.v1.ExecUpdate
	31, // 36: agentsessions.v1.Sessions.Replay:output_type -> agentsessions.v1.LogRecord
	6,  // 37: agentsessions.v1.Sessions.Cancel:output_type -> agentsessions.v1.Session
	6,  // 38: agentsessions.v1.Sessions.Heartbeat:output_type -> agentsessions.v1.Session
	6,  // 39: agentsessions.v1.Sessions.Pause:output_type -> agentsessions.v1.Session
	6,  // 40: agentsessions.v1.Sessions.Suspend:output_type -> agentsessions.v1.Session
	6,  // 41: agentsessions.v1.Sessions.Resume:output_type -> agentsessions.v1.Session
	18, // 42: agentsessions.v1.Sessions.Fork:output_type -> agentsessions.v1.ForkResponse
	31, // [31:43] is the sub-list for method output_type
	19, // [19:31] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_session_proto_init() }
func file_session_proto_init() {
	if File_session_proto != nil {
		return
	}
	file_common_proto_init()
	file_session_proto_msgTypes[0].OneofWrappers = []any{
		(*SnapshotRef_Local)(nil),
		(*SnapshotRef_ExternalUri)(nil),
	}
	file_session_proto_msgTypes[18].OneofWrappers = []any{
		(*ExecUpdate_Record)(nil),
		(*ExecUpdate_Delta)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_session_proto_rawDesc), len(file_session_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_session_proto_goTypes,
		DependencyIndexes: file_session_proto_depIdxs,
		EnumInfos:         file_session_proto_enumTypes,
		MessageInfos:      file_session_proto_msgTypes,
	}.Build()
	File_session_proto = out.File
	file_session_proto_goTypes = nil
	file_session_proto_depIdxs = nil
}
